/* DuiX — datos del juego: villanos, repaso, tienda, logros */
(function (root) {
  'use strict';

  /* ---------- Villanos / distritos (uno por tema) ---------- */
  const VILLAINS = [
    {
      id: 'intervalos', n: 1, topic: 'intervalos', name: 'Corchetto', title: 'Señor de los Extremos', district: 'Muelle de los Extremos', tema: 'Intervalos',
      body: 'brute', glyph: '[ )', pal: { main: '#2bb3a3', shade: '#177a70', light: '#7ff0dd', accent: '#ffd23f', eye: '#ff4d4d' }, sky: ['#0d2a4a', '#1c6f8f'], glow: '#2bb3a3',
      intro: '¡Nadie cruza mis fronteras! Yo decido quién entra al intervalo… y quién se queda afuera.',
      defeat: 'Mis extremos… ¡estaban abiertos todo el tiempo!',
    },
    {
      id: 'fracciones', n: 2, topic: 'fracciones', name: 'Don Quebrado', title: 'El Partido en Dos', district: 'Mercado Fraccionado', tema: 'Operaciones con fracciones',
      body: 'blob', glyph: '½', pal: { main: '#ff8fa3', shade: '#c9486a', light: '#ffd0da', accent: '#ffe066', eye: '#3a0f26' }, sky: ['#3a1230', '#a8456b'], glow: '#ff8fa3',
      intro: 'Te voy a romper en pedacitos… ¡y sin común denominador!',
      defeat: 'Me… me simplificaron a la mínima expresión.',
    },
    {
      id: 'factorizacion', n: 3, topic: 'factorizacion', name: 'Primo Rex', title: 'El Desarmador', district: 'Fábrica de Factores', tema: 'Factorización',
      body: 'dino', glyph: '(·)(·)', pal: { main: '#63c132', shade: '#3a7d1a', light: '#b6f27a', accent: '#ff7b00', eye: '#ffef5c' }, sky: ['#14300f', '#4b8a2a'], glow: '#63c132',
      intro: '¡RAAAWR! Todo número se rompe en primos… ¡y tú serás el siguiente!',
      defeat: 'Me descompusieron… en factores primos.',
    },
    {
      id: 'polinomios', n: 4, topic: 'polinomios', name: 'Polinomiaca', title: 'La de Mil Términos', district: 'Torre de los Mil Términos', tema: 'Operaciones entre polinomios',
      body: 'witch', glyph: 'xⁿ', pal: { main: '#9b5de5', shade: '#5f2fa0', light: '#d3b0ff', accent: '#f15bb5', eye: '#fff275' }, sky: ['#1d0f3d', '#6a3fb5'], glow: '#9b5de5',
      intro: 'Sumo, resto, multiplico… ¡y cada término que te toque será tu perdición!',
      defeat: 'Mis términos semejantes… ¡se han cancelado!',
    },
    {
      id: 'plano', n: 5, topic: 'plano', name: 'Lord Descartes', title: 'El Descartado', district: 'Plaza Cartesiana', tema: 'Plano cartesiano',
      body: 'gentleman', glyph: '(x,y)', pal: { main: '#e4c9a3', shade: '#a98453', light: '#fff0d6', accent: '#2f6bff', eye: '#1a1033' }, sky: ['#10233f', '#3a6ea5'], glow: '#4da3ff',
      intro: 'Yo inventé el plano. Cada punto de esta ciudad tiene su lugar… y el tuyo es la derrota.',
      defeat: 'Descartado… otra vez. ¡Qué irónico!',
    },
    {
      id: 'desigualdades', n: 6, topic: 'desigualdades', name: 'Cocodrilo Desigual', title: 'La Boca que Devora', district: 'Pantano de la Boca Abierta', tema: 'Desigualdades',
      body: 'croc', glyph: '<', pal: { main: '#4cbb17', shade: '#2a7a0b', light: '#a8f072', accent: '#ffd23f', eye: '#ffcf33' }, sky: ['#0d2a17', '#2f7d3a'], glow: '#4cbb17',
      intro: '¡ÑAM! Siempre me como al número más grande. ¿Cuál será el tuyo?',
      defeat: 'Me dieron la vuelta… ¡y cambié de sentido!',
    },
    {
      id: 'funciones', n: 7, topic: 'funciones', name: 'F-9000', title: 'La Máquina Entra-Sale', district: 'Laboratorio Entra-Sale', tema: 'Funciones y operaciones entre funciones',
      body: 'robot', glyph: 'f(x)', pal: { main: '#b8c4d6', shade: '#6f7f99', light: '#f0f5ff', accent: '#ff3b3b', eye: '#ff3b3b' }, sky: ['#0b1424', '#2b4a78'], glow: '#7db2ff',
      intro: 'ENTRADA DETECTADA. SALIDA ÚNICA GARANTIZADA. RESISTENCIA: INÚTIL.',
      defeat: 'ERROR… dos salidas para una misma entrada…',
    },
    {
      id: 'desplazamientos', n: 8, topic: 'desplazamientos', name: 'Fantasma Desfase', title: 'El que Mueve Todo', district: 'Cementerio de las Traslaciones', tema: 'Desplazamientos en el plano',
      body: 'ghost', glyph: '→↑', pal: { main: '#d9e4ff', shade: '#8ea3d9', light: '#ffffff', accent: '#5ce1e6', eye: '#1a1033' }, sky: ['#141033', '#4b3f8f'], glow: '#9ab0ff',
      intro: 'Uuuh… muevo tu gráfica a la izquierda… ¡pero parece que va a la derecha!',
      defeat: 'Me… reflejaron… en el eje equivocado…',
    },
    {
      id: 'tabulaciones', n: 9, topic: 'tabulaciones', name: 'Tabulón', title: 'El Tirano de la Tabla', district: 'Bulevar de las Tablas', tema: 'Tabulaciones',
      body: 'tower', glyph: 'x|y', pal: { main: '#f4a259', shade: '#b8672a', light: '#ffd9aa', accent: '#2e2a5b', eye: '#2e2a5b' }, sky: ['#2b1a0d', '#a8642a'], glow: '#f4a259',
      intro: 'Cada fila, cada columna… ¡todo en orden o te encierro en mi tabla!',
      defeat: 'Mi tabla… ¡se quedó sin filas!',
    },
    {
      id: 'potenciacion', n: 10, topic: 'potenciacion', name: 'Potentor', title: 'El Elevado', district: 'Gimnasio Exponencial', tema: 'Potenciación',
      body: 'muscle', glyph: 'xⁿ', pal: { main: '#ef476f', shade: '#a12244', light: '#ff9db5', accent: '#ffd166', eye: '#fff275' }, sky: ['#2a0a17', '#a3294a'], glow: '#ef476f',
      intro: '¡Mis músculos crecen EXPONENCIALMENTE! ¿Cuánto es 2 elevado a mi poder?',
      defeat: 'Mi exponente… ¡se hizo cero!',
    },
    {
      id: 'composicion', n: 11, topic: 'composicion', name: 'Matrioska', title: 'La Compuesta', district: 'Bazar de Muñecas Rusas', tema: 'Composición de funciones',
      body: 'egg', glyph: 'f∘g', pal: { main: '#e63946', shade: '#9d1d2a', light: '#ff8a93', accent: '#ffd166', eye: '#1a1033' }, sky: ['#2a1020', '#8a2c4a'], glow: '#ff5d6c',
      intro: 'Dentro de mí hay otra… y dentro de ella, otra más. ¡Primero g, después f!',
      defeat: 'Me abrieron… ¡y ya no quedaba nadie adentro!',
    },
    {
      id: 'radicales', n: 12, topic: 'radicales', name: 'Raizón', title: 'El Radical', district: 'Mina Radical', tema: 'Exponentes y radicales',
      body: 'miner', glyph: '√', pal: { main: '#a67c52', shade: '#6b4a2a', light: '#d9b48a', accent: '#ffd23f', eye: '#fff275' }, sky: ['#1b120a', '#5b3d22'], glow: '#d9a05b',
      intro: 'Vivo bajo tierra, en la raíz de todos los problemas. ¡Ven a sacarme si puedes!',
      defeat: 'Me racionalizaron… ¡sin dejarme raíz en el denominador!',
    },
    {
      id: 'logaritmos', n: 13, topic: 'logaritmos', name: 'Logarritmia', title: 'La Deshacedora de Potencias', district: 'Puerto del Log', tema: 'Logaritmos y funciones inversas',
      body: 'squid', glyph: 'log', pal: { main: '#3a86ff', shade: '#1b4aa8', light: '#8ec0ff', accent: '#ffbe0b', eye: '#fff275' }, sky: ['#04122e', '#0c4c8f'], glow: '#3a86ff',
      intro: 'Deshago tus potencias como la marea deshace la arena. ¿A qué exponente vas a caer?',
      defeat: 'Mi inversa… ¡me devolvió al principio!',
    },
    {
      id: 'trigonometria', n: 14, topic: 'trigonometria', name: 'Tangenta', title: 'Reina de las Ondas', district: 'Observatorio de las Ondas', tema: 'Funciones trigonométricas',
      body: 'queen', glyph: 'sen', pal: { main: '#f8c8ff', shade: '#b158c9', light: '#ffeaff', accent: '#ffd166', eye: '#7a1fa2' }, sky: ['#170a33', '#7a3fa8'], glow: '#e07cff',
      intro: 'Subo, bajo, me repito cada 2π. ¡Ninguna onda escapa de mi corona!',
      defeat: 'Mi período… ¡se acabó!',
    },
    {
      id: 'limites', n: 15, topic: 'limites', name: 'Aproximín', title: 'El Que Nunca Llega', district: 'Frontera del Límite', tema: 'Límites',
      body: 'ghost', glyph: 'lím', pal: { main: '#2ec4b6', shade: '#0f7a70', light: '#9ff5ea', accent: '#ffd166', eye: '#0b2a33' }, sky: ['#021a1f', '#0f6b6b'], glow: '#2ec4b6',
      intro: 'Me acerco… me acerco… ¡pero jamás me toco! ¿Hacia dónde voy cuando x se acerca?',
      defeat: 'Me tabularon por los dos lados… ¡y por fin llegué a mi límite!',
    },
    {
      id: 'indeterminado', n: 16, topic: 'mix', name: 'El Indeterminado', title: 'El Jefe del Vacío', district: 'El Vacío 0/0', tema: 'Todos los temas',
      body: 'void', glyph: '0/0', pal: { main: '#2a1a4a', shade: '#100a20', light: '#7a4fd1', accent: '#ff3b6b', eye: '#ff3b6b' }, sky: ['#000000', '#2a0a3d'], glow: '#b14cff', boss: true,
      intro: 'Nací de dividir entre cero. Ni valgo algo… ni valgo nada. ¡Y voy a borrarte de esta ciudad!',
      defeat: 'Detrás de mí… ¡alguien más movía los hilos!',
    },
    {
      id: 'duinity', n: 17, topic: 'mix', name: 'Duinity', title: 'El Infinito', district: 'Dimensión Infinita', tema: 'Modo Duinity (sin fin)',
      body: 'king', glyph: '∞', pal: { main: '#ffd23f', shade: '#c98900', light: '#fff2a8', accent: '#ff3b6b', eye: '#2a0a3d' }, sky: ['#0a0020', '#4a1a8f'], glow: '#ffd23f', boss: true, endless: true,
      intro: 'Yo soy el límite al que nadie llega. ¿Cuánto puedes resistir contra el infinito?',
      defeat: '¡Imposible… llegaste hasta donde yo no acababa!',
    },
  ];

  /* ---------- Repaso rápido por tema ---------- */
  const REPASO = {
    intervalos: [
      'Un intervalo es el conjunto de números que hay entre dos extremos. Se escribe con corchetes o paréntesis.',
      '[ ] (corchete) = el extremo SÍ entra (≤ o ≥).  ( ) (paréntesis) = el extremo NO entra (< o >).',
      'Con ∞ y −∞ siempre se usa paréntesis: el infinito no es un número que se pueda alcanzar.',
      'Unión A ∪ B: todo lo que está en A o en B. Intersección A ∩ B: solo lo que está en los dos a la vez. Dibuja ambos en la recta numérica y mira dónde se juntan o se solapan.',
      'Ejemplo: −2 < x ≤ 5 se escribe (−2, 5]  (el −2 no entra, el 5 sí).',
      'Ejemplo: [1, 6) ∩ (3, 9] = (3, 6), porque lo que comparten empieza después del 3 y termina antes del 6.',
      '📖 Stewart, Precálculo §1.1 “Números reales”, apartado Intervalos (p. 2).',
    ],
    fracciones: [
      'Suma y resta: busca un denominador común (el mínimo común múltiplo) y luego suma o resta SOLO los numeradores.',
      'Nunca sumes los denominadores: 1/2 + 1/3 no es 2/5.',
      'Producto: numerador por numerador y denominador por denominador. Puedes simplificar en cruz antes de multiplicar.',
      'División: copia la primera, cambia ÷ por × y voltea la segunda: a/b ÷ c/d = a/b × d/c.',
      'Simplificar: divide numerador y denominador entre su máximo común divisor.',
      'Ejemplo: 2/3 + 1/4 = 8/12 + 3/12 = 11/12.',
      'Ejemplo: 3/4 ÷ 3/8 = 3/4 × 8/3 = 24/12 = 2.',
      '📖 Stewart, Precálculo §1.1 “Números reales” (operaciones con fracciones) y §1.4 “Expresiones racionales” (p. 35).',
    ],
    factorizacion: [
      'Factorizar es escribir una expresión como un producto. Siempre empieza sacando el factor común mayor.',
      'Diferencia de cuadrados: a² − b² = (a − b)(a + b).',
      'Trinomio cuadrado perfecto: a² + 2ab + b² = (a + b)²  y  a² − 2ab + b² = (a − b)².',
      'Trinomio x² + bx + c: busca dos números que MULTIPLIQUEN c y SUMEN b.',
      'Suma de cubos: a³ + b³ = (a + b)(a² − ab + b²).  Diferencia de cubos: a³ − b³ = (a − b)(a² + ab + b²).',
      'Agrupación: agrupa de dos en dos, saca factor común en cada grupo y luego el factor que se repite.',
      'Ejemplo: x² + 5x + 6 = (x + 2)(x + 3), porque 2 · 3 = 6 y 2 + 3 = 5.',
      'Ejemplo: 9x² − 16 = (3x)² − 4² = (3x − 4)(3x + 4).',
      '📖 Stewart, Precálculo §1.3 “Expresiones algebraicas”: Fórmulas especiales de factorización (p. 24).',
    ],
    polinomios: [
      'Un polinomio es una suma de términos como a·xⁿ con n entero ≥ 0. El grado es el mayor exponente.',
      'Suma y resta: solo se combinan términos semejantes (mismo exponente). Al restar, cambia el signo de TODOS los términos del segundo polinomio.',
      'Multiplicación: propiedad distributiva; cada término del primero por cada término del segundo. En binomios: (a + b)(c + d) = ac + ad + bc + bd.',
      'El grado de un producto es la suma de los grados de los factores.',
      'Teorema del Residuo: al dividir P(x) entre (x − c), el residuo es P(c).',
      'División sintética: escribe los coeficientes, baja el primero, multiplícalo por c, súmalo a la siguiente columna y repite.',
      'Ejemplo: (x + 2)(x − 5) = x² − 5x + 2x − 10 = x² − 3x − 10.',
      'Ejemplo: P(x) = x² + 3x − 1 entre (x − 2) deja residuo P(2) = 4 + 6 − 1 = 9.',
      '📖 Stewart, Precálculo §1.3 (p. 24), §3.3 “División de polinomios” (p. 246) y §3.4 (Teorema del Residuo).',
    ],
    plano: [
      'Plano cartesiano: eje x horizontal, eje y vertical. Un punto es (x, y). Cuadrantes: I (+, +), II (−, +), III (−, −), IV (+, −).',
      'Reflexión: en el eje x cambia el signo de y; en el eje y cambia el signo de x; en el origen cambian los dos.',
      'Distancia entre (x₁, y₁) y (x₂, y₂):  d = √[(x₂ − x₁)² + (y₂ − y₁)²].',
      'Punto medio:  ((x₁ + x₂)/2 , (y₁ + y₂)/2).',
      'Pendiente:  m = (y₂ − y₁)/(x₂ − x₁).  Recta por un punto: y − y₁ = m(x − x₁).  Forma pendiente–ordenada: y = mx + b.',
      'Ejemplo: entre (1, 2) y (4, 6): d = √(3² + 4²) = 5; punto medio (2,5 ; 4); m = 4/3.',
      '📖 Stewart, Precálculo §1.8 “Geometría de coordenadas” (p. 83) y §1.10 “Rectas” (p. 106).',
    ],
    desigualdades: [
      'Se resuelven como una ecuación, PERO si multiplicas o divides por un número negativo, el signo de la desigualdad se invierte.',
      'Desigualdad compuesta a < expresión < b: opera en los tres miembros a la vez.',
      'Valor absoluto: |u| < c ⇔ −c < u < c (una franja).   |u| > c ⇔ u < −c  o  u > c (dos partes).',
      'Desigualdades no lineales: pasa todo a un lado, factoriza, encuentra dónde vale 0 y prueba el signo en cada zona de la recta.',
      'Ejemplo: −2x + 3 > 7 → −2x > 4 → x < −2  (¡el signo se invirtió!).',
      'Ejemplo: |x − 1| ≤ 3 → −3 ≤ x − 1 ≤ 3 → −2 ≤ x ≤ 4 → [−2, 4].',
      '📖 Stewart, Precálculo §1.7 “Desigualdades”, incluida la parte de Desigualdades con valor absoluto (p. 73).',
    ],
    funciones: [
      'Una función asigna a cada entrada x exactamente UNA salida y = f(x).',
      'Dominio: los valores de x permitidos (no se divide entre 0 ni hay raíz cuadrada de un negativo). Rango: los valores de y que salen.',
      'Para evaluar f(a), sustituye x por a usando paréntesis.',
      'Operaciones: (f + g)(x) = f(x) + g(x);  (f · g)(x) = f(x) · g(x);  (f / g)(x) = f(x) / g(x) con g(x) ≠ 0.',
      'Prueba de la recta vertical: si alguna recta vertical corta la gráfica más de una vez, no es una función.',
      'Ejemplo: f(x) = x² − 3x → f(4) = 16 − 12 = 4.',
      'Ejemplo: dominio de f(x) = √(x − 2)/(x − 5): x − 2 ≥ 0 y x ≠ 5, o sea [2, 5) ∪ (5, ∞).',
      '📖 Stewart, Precálculo §2.1 “¿Qué es una función?” (p. 142), §2.2 (p. 152) y §2.6 “Combinación de funciones” (p. 190).',
    ],
    desplazamientos: [
      'FUERA de la función, el movimiento es vertical y “tal cual”: f(x) + c sube c unidades; f(x) − c baja c unidades.',
      'DENTRO del paréntesis, el movimiento es horizontal y “al revés”: f(x − c) va c a la derecha; f(x + c) va c a la izquierda.',
      'y = −f(x) refleja la gráfica respecto al eje x;  y = f(−x) la refleja respecto al eje y.',
      'El vértice de y = a(x − h)² + k es el punto (h, k).',
      'Para mover un punto (x, y): derecha suma a x, izquierda resta a x, arriba suma a y, abajo resta a y.',
      'Ejemplo: y = (x + 2)² − 3 es y = x² movida 2 a la izquierda y 3 hacia abajo; su vértice es (−2, −3).',
      '📖 Stewart, Precálculo §2.5 “Transformaciones de funciones”: desplazamientos verticales y horizontales (p. 179).',
    ],
    tabulaciones: [
      'Tabular es evaluar f en varios valores de x y ordenar los resultados en una tabla (x | y).',
      'Función lineal: cuando x sube 1, y cambia SIEMPRE lo mismo (esa cantidad es la pendiente). El valor de y cuando x = 0 es la ordenada al origen b.',
      'Función cuadrática: los cambios de y no son iguales; y con valores de x igualmente espaciados, los cambios de esos cambios sí son constantes. Además hay simetría alrededor del vértice.',
      'Para hallar la fórmula desde una tabla: mira f(0) (ese es b) y luego cuánto cambia y por cada paso de x.',
      'Ejemplo: f(x) = 2x − 1 con x = −1, 0, 1, 2 da y = −3, −1, 1, 3 (sube de 2 en 2).',
      '📖 Stewart, Precálculo §2.1: representar una función de forma numérica (tablas) y algebraica (p. 142) y §2.2 (p. 152).',
    ],
    potenciacion: [
      'Misma base al multiplicar: se SUMAN los exponentes:  xᵐ · xⁿ = xᵐ⁺ⁿ.',
      'Misma base al dividir: se RESTAN los exponentes:  xᵐ / xⁿ = xᵐ⁻ⁿ.',
      'Potencia de una potencia: se MULTIPLICAN los exponentes:  (xᵐ)ⁿ = xᵐⁿ.   Y (ab)ⁿ = aⁿ · bⁿ.',
      'x⁰ = 1 (si x ≠ 0)  y  x⁻ⁿ = 1/xⁿ.',
      'Cuidado con el signo: −3² = −9 (el exponente solo afecta al 3), pero (−3)² = 9.',
      'Ejemplo: (2x³)² · x = 4x⁶ · x = 4x⁷.',
      '📖 Stewart, Precálculo §1.2 “Exponentes y radicales”: Leyes de exponentes (p. 12).',
    ],
    composicion: [
      '(f ∘ g)(x) = f(g(x)): primero aplicas g (la de adentro) y el resultado se lo das a f.',
      'El orden importa: en general f ∘ g NO es igual a g ∘ f.',
      'Para evaluar (f ∘ g)(a): calcula g(a) primero y luego f de ese número.',
      'Para hallar la fórmula: sustituye toda la fórmula de g en la x de f y desarrolla.',
      'Para descomponer h(x): pregúntate qué se le hace primero a x; eso es g. Lo que se hace después es f.',
      'Ejemplo: f(x) = x² y g(x) = x + 1 → (f ∘ g)(x) = (x + 1)² = x² + 2x + 1, pero (g ∘ f)(x) = x² + 1.',
      '📖 Stewart, Precálculo §2.6 “Combinación de funciones”: Composición de funciones (p. 190).',
    ],
    radicales: [
      'ⁿ√a = a^(1/n)  y  ⁿ√(aᵐ) = a^(m/n): el exponente va arriba y el índice de la raíz abajo.',
      '√(ab) = √a · √b. Para simplificar, saca los cuadrados perfectos: √50 = √(25 · 2) = 5√2.',
      'Solo se suman o restan radicales semejantes (misma raíz): 3√2 + 5√2 = 8√2.',
      'Racionalizar es quitar la raíz del denominador: 1/√a = √a/a.',
      'Si el denominador es √a + √b, multiplica arriba y abajo por el conjugado (√a − √b).',
      'Ejemplo: 8^(2/3) = (∛8)² = 2² = 4.',
      '📖 Stewart, Precálculo §1.2 “Exponentes y radicales”: Radicales, Exponentes racionales y Racionalización del denominador (p. 12).',
    ],
    logaritmos: [
      'log_b x = y significa bʸ = x. El logaritmo ES el exponente.',
      'Casos útiles: log_b 1 = 0;  log_b b = 1;  log_b(bˣ) = x;  b^(log_b x) = x.  ln es el logaritmo de base e.',
      'Leyes: log(A·B) = log A + log B;  log(A/B) = log A − log B;  log(Aᶜ) = c · log A.',
      'Ecuación exponencial: iguala las bases (3ˣ = 27 → x = 3) o aplica logaritmo a ambos lados.',
      'Inversa de f: (1) escribe y = f(x), (2) despeja x, (3) intercambia x e y. Solo existe si f es uno a uno (Prueba de la Recta Horizontal).',
      'La inversa de bˣ es log_b x, y f(f⁻¹(x)) = x.',
      'Ejemplo: log₂ 8 + log₂ 4 = 3 + 2 = 5 = log₂ 32.',
      '📖 Stewart, Precálculo §2.7 “Funciones uno a uno y sus inversas” (p. 199), §4.3 (p. 315), §4.4 “Leyes de logaritmos” (p. 325) y §4.5 (p. 331).',
    ],
    trigonometria: [
      'Radianes y grados: 180° = π rad. De grados a radianes multiplica por π/180; de radianes a grados, por 180/π.',
      'Triángulo rectángulo: sen = opuesto/hipotenusa; cos = adyacente/hipotenusa; tan = opuesto/adyacente (SOH-CAH-TOA).',
      'En la circunferencia unitaria, el punto del ángulo θ es (cos θ, sen θ).',
      'Valores clave: sen 30° = 1/2, sen 45° = √2/2, sen 60° = √3/2 (el coseno va al revés).',
      'Signos por cuadrante: I todas positivas, II solo sen, III solo tan, IV solo cos.',
      'Ángulo de referencia: el ángulo agudo que forma con el eje x. Úsalo y pon el signo del cuadrante.',
      'Identidad pitagórica: sen²θ + cos²θ = 1.  En y = A·sen(Bx): amplitud |A| y período 2π/|B|.',
      'Ejemplo: sen 150°: ángulo de referencia 30°, cuadrante II (sen positivo) → 1/2.',
      '📖 Stewart, Precálculo §6.1 “Medida de un ángulo” (p. 434), §6.2 (p. 443), §6.3 (p. 451), §5.1 “La circunferencia unitaria” (p. 370) y §5.3 (p. 386).',
    ],
    limites: [
      'Límite (idea intuitiva): lím(x→a) f(x) = L significa que f(x) se acerca a L cuando x se acerca a a, sin importar lo que pase exactamente en x = a.',
      'Tabulación: evalúa f en valores cada vez más cercanos a a por la izquierda (a − 0,1; a − 0,01…) y por la derecha (a + 0,1; a + 0,01…). Si ambos lados se acercan al mismo número L, ese es el límite.',
      'Si los dos lados se acercan a números distintos, el límite NO existe.',
      'Cálculo básico: si f es un polinomio, sustituye x = a. Si sale 0/0 (indeterminado), factoriza y simplifica (o racionaliza con el conjugado) y luego sustituye.',
      'Límites al infinito: en (px + q)/(rx + s) con x → ∞, el límite es p/r (los términos constantes pesan cada vez menos).',
      'Ejemplo: lím(x→3) (x² − 9)/(x − 3) = lím(x→3) (x + 3) = 6.',
      '📖 Stewart, Precálculo, Cap. 13 “Límites: una mirada previa al cálculo” §13.1 “Hallar límites numérica y gráficamente” y §13.2 “Hallar límites algebraicamente”.',
    ],
    mix: [
      'Aquí entran TODOS los temas: intervalos, fracciones, factorización, polinomios, plano, desigualdades, funciones, desplazamientos, tablas, potencias, composición, radicales, logaritmos, trigonometría.',
      'Lee con calma cada pregunta y descarta opciones absurdas.',
      'Usa la Pista (te da una idea clara y descarta una opción) y tu Superpoder cuando lo necesites.',
      'Si dudas de un tema, repásalo antes en su distrito. Todos traen la referencia al libro de Stewart.',
    ],
  };

  /* ---------- Tienda / vestidor ---------- */
  const RARITY = { comun: { name: 'Común', color: '#9fb3c8' }, raro: { name: 'Raro', color: '#4da3ff' }, epico: { name: 'Épico', color: '#c77dff' }, legendario: { name: 'Legendario', color: '#ffc933' } };

  const CATS = [
    { id: 'suit', name: 'Traje', icon: '👕' },
    { id: 'hair', name: 'Pelo', icon: '💇' },
    { id: 'mask', name: 'Cabeza', icon: '🎭' },
    { id: 'wings', name: 'Alas', icon: '🦋' },
    { id: 'cape', name: 'Capa', icon: '🧣' },
    { id: 'pet', name: 'Mascota', icon: '🐉' },
    { id: 'weapon', name: 'Arma', icon: '⚔️' },
    { id: 'emblem', name: 'Emblema', icon: '⭐' },
    { id: 'amulet', name: 'Amuleto', icon: '🛡️' },
    { id: 'emote', name: 'Emotes', icon: '💃' },
  ];

  const ITEMS = [
    // ---- Trajes: 4 colores base gratis por género (los 8 son de todos) + el resto se compra
    { id: 'suit-rojo', cat: 'suit', name: 'Rojo Héroe', rarity: 'comun', price: 0, main: '#e63946', shade: '#9d1d2a', accent: '#ffd23f', g: 'm' },
    { id: 'suit-azul', cat: 'suit', name: 'Azul Límite', rarity: 'comun', price: 0, main: '#2f6bff', shade: '#1b3ea8', accent: '#ffffff', g: 'm' },
    { id: 'suit-verde', cat: 'suit', name: 'Verde Radical', rarity: 'comun', price: 0, main: '#2ecc71', shade: '#1a8a4a', accent: '#ffe66d', g: 'm' },
    { id: 'suit-amarillo', cat: 'suit', name: 'Amarillo Rayo', rarity: 'comun', price: 0, main: '#ffcf33', shade: '#c99a00', accent: '#e63946', g: 'm' },
    { id: 'suit-rosa', cat: 'suit', name: 'Rosa Fucsia', rarity: 'comun', price: 0, main: '#ff4fa3', shade: '#b62a72', accent: '#ffffff', g: 'f' },
    { id: 'suit-morado', cat: 'suit', name: 'Morado Nova', rarity: 'comun', price: 0, main: '#8e44ff', shade: '#5a24b0', accent: '#ff7ad9', g: 'f' },
    { id: 'suit-cian', cat: 'suit', name: 'Cian Cuántico', rarity: 'comun', price: 0, main: '#16d5d5', shade: '#0b8f96', accent: '#ffffff', g: 'f' },
    { id: 'suit-naranja', cat: 'suit', name: 'Naranja Solar', rarity: 'comun', price: 0, main: '#ff8a1f', shade: '#c25a00', accent: '#3b1a00', g: 'f' },
    { id: 'suit-lima', cat: 'suit', name: 'Lima Neón', rarity: 'comun', price: 60, main: '#9be34a', shade: '#5f9a1e', accent: '#1a1033' },
    { id: 'suit-blanco', cat: 'suit', name: 'Blanco Nova', rarity: 'comun', price: 70, main: '#f3f6ff', shade: '#b7c0dd', accent: '#e63946' },
    { id: 'suit-vino', cat: 'suit', name: 'Vino Carmesí', rarity: 'raro', price: 90, main: '#b3204d', shade: '#761333', accent: '#ffd23f' },
    { id: 'suit-negro', cat: 'suit', name: 'Negro Sombra', rarity: 'raro', price: 150, main: '#2b2d42', shade: '#14151f', accent: '#ff3b3b' },
    { id: 'suit-plata', cat: 'suit', name: 'Plata Vectorial', rarity: 'epico', price: 300, main: '#cfd8e6', shade: '#8a97ad', accent: '#2f6bff' },
    { id: 'suit-dorado', cat: 'suit', name: 'Dorado Sigma', rarity: 'legendario', price: 650, main: '#ffc933', shade: '#c98900', accent: '#ffffff' },
    // fantasía
    { id: 'suit-mago', cat: 'suit', name: 'Túnica de Mago', rarity: 'raro', price: 180, style: 'robe', main: '#5b3fd1', shade: '#3a2591', accent: '#ffd23f' },
    { id: 'suit-elfo', cat: 'suit', name: 'Túnica Élfica', rarity: 'raro', price: 180, style: 'robe', main: '#2f9e5a', shade: '#1d6b3b', accent: '#f2e6b1' },
    { id: 'suit-caballero', cat: 'suit', name: 'Armadura de Caballero', rarity: 'epico', price: 340, style: 'armor', main: '#b9c4d6', shade: '#7d8aa3', accent: '#2f6bff' },
    { id: 'suit-dragon', cat: 'suit', name: 'Armadura Dracónica', rarity: 'epico', price: 420, style: 'armor', main: '#a3182b', shade: '#62101b', accent: '#ffb01f' },
    { id: 'suit-real', cat: 'suit', name: 'Armadura Real', rarity: 'legendario', price: 780, style: 'armor', main: '#ffc933', shade: '#c98900', accent: '#e63946' },
    // ---- Peinados (5 gratis, el resto se compra; el color del pelo es libre)
    { id: 'hair-corto', cat: 'hair', name: 'Corto', rarity: 'comun', price: 0, hs: 'corto' },
    { id: 'hair-pinchos', cat: 'hair', name: 'Pinchos', rarity: 'comun', price: 0, hs: 'pinchos' },
    { id: 'hair-calvo', cat: 'hair', name: 'Rapado', rarity: 'comun', price: 0, hs: 'calvo' },
    { id: 'hair-largo', cat: 'hair', name: 'Melena Larga', rarity: 'comun', price: 0, hs: 'largo' },
    { id: 'hair-coleta', cat: 'hair', name: 'Coleta', rarity: 'comun', price: 0, hs: 'coleta' },
    { id: 'hair-bob', cat: 'hair', name: 'Bob con Flequillo', rarity: 'comun', price: 50, hs: 'bob' },
    { id: 'hair-mono', cat: 'hair', name: 'Moño Alto', rarity: 'comun', price: 50, hs: 'mono' },
    { id: 'hair-dobles', cat: 'hair', name: 'Coletas Dobles', rarity: 'comun', price: 60, hs: 'dobles' },
    { id: 'hair-afro', cat: 'hair', name: 'Afro', rarity: 'comun', price: 60, hs: 'afro' },
    { id: 'hair-trenzas', cat: 'hair', name: 'Trenzas', rarity: 'raro', price: 90, hs: 'trenzas' },
    { id: 'hair-cresta', cat: 'hair', name: 'Cresta Punk', rarity: 'raro', price: 90, hs: 'cresta' },
    { id: 'hair-cristal', cat: 'hair', name: 'Cristales', rarity: 'epico', price: 240, hs: 'cristal' },
    { id: 'hair-llamas', cat: 'hair', name: 'Cabellera de Fuego', rarity: 'legendario', price: 520, hs: 'llamas' },
    // ---- Cabeza (máscaras, cascos y accesorios)
    { id: 'mask-none', cat: 'mask', name: 'Sin nada', rarity: 'comun', price: 0 },
    { id: 'mask-antifaz', cat: 'mask', name: 'Antifaz', rarity: 'comun', price: 0 },
    { id: 'mask-gafas', cat: 'mask', name: 'Gafas de Laboratorio', rarity: 'comun', price: 70 },
    { id: 'mask-elfo', cat: 'mask', name: 'Orejas Élficas', rarity: 'comun', price: 90 },
    { id: 'mask-visor', cat: 'mask', name: 'Visor Cyber', rarity: 'raro', price: 100 },
    { id: 'mask-gato', cat: 'mask', name: 'Máscara Felina', rarity: 'raro', price: 120 },
    { id: 'mask-ninja', cat: 'mask', name: 'Capucha Ninja', rarity: 'raro', price: 140 },
    { id: 'mask-halo', cat: 'mask', name: 'Aureola', rarity: 'raro', price: 140 },
    { id: 'mask-mago', cat: 'mask', name: 'Sombrero de Mago', rarity: 'raro', price: 150 },
    { id: 'mask-robot', cat: 'mask', name: 'Casco Robot', rarity: 'epico', price: 260 },
    { id: 'mask-caballero', cat: 'mask', name: 'Yelmo de Caballero', rarity: 'epico', price: 300 },
    { id: 'mask-cuernos', cat: 'mask', name: 'Cuernos de Dragón', rarity: 'epico', price: 320 },
    { id: 'mask-corona', cat: 'mask', name: 'Corona Infinita', rarity: 'legendario', price: 700 },
    // ---- Alas
    { id: 'wing-none', cat: 'wings', name: 'Sin alas', rarity: 'comun', price: 0 },
    { id: 'wing-hada', cat: 'wings', name: 'Alas de Hada', rarity: 'raro', price: 180, wk: 'hada' },
    { id: 'wing-murcielago', cat: 'wings', name: 'Alas de Murciélago', rarity: 'raro', price: 200, wk: 'bat' },
    { id: 'wing-angel', cat: 'wings', name: 'Alas de Ángel', rarity: 'epico', price: 300, wk: 'angel' },
    { id: 'wing-mecanica', cat: 'wings', name: 'Alas Mecánicas', rarity: 'epico', price: 340, wk: 'mech' },
    { id: 'wing-dragon', cat: 'wings', name: 'Alas de Dragón', rarity: 'epico', price: 380, wk: 'dragon' },
    { id: 'wing-fenix', cat: 'wings', name: 'Alas de Fénix', rarity: 'legendario', price: 800, wk: 'fenix' },
    // ---- Capas
    { id: 'cape-none', cat: 'cape', name: 'Sin capa', rarity: 'comun', price: 0 },
    { id: 'cape-corta', cat: 'cape', name: 'Capa Corta', rarity: 'comun', price: 0, style: 'short', c1: '#d62839', c2: '#8c1a26' },
    { id: 'cape-larga-azul', cat: 'cape', name: 'Capa Larga Azul', rarity: 'comun', price: 50, style: 'long', c1: '#2f6bff', c2: '#1b3ea8' },
    { id: 'cape-larga-negra', cat: 'cape', name: 'Capa de Medianoche', rarity: 'raro', price: 110, style: 'long', c1: '#2b2d42', c2: '#12131d' },
    { id: 'cape-dorada', cat: 'cape', name: 'Capa Dorada', rarity: 'epico', price: 320, style: 'long', c1: '#ffc933', c2: '#c98900' },
    { id: 'cape-fuego', cat: 'cape', name: 'Capa de Fuego', rarity: 'legendario', price: 700, style: 'flame', c1: '#ff7b00', c2: '#ff3b1f' },
    // ---- Mascotas
    { id: 'pet-none', cat: 'pet', name: 'Sin mascota', rarity: 'comun', price: 0 },
    { id: 'pet-slime', cat: 'pet', name: 'Slime Saltarín', rarity: 'comun', price: 80, pk: 'slime' },
    { id: 'pet-gato', cat: 'pet', name: 'Gato Ninja', rarity: 'comun', price: 100, pk: 'gato' },
    { id: 'pet-dron', cat: 'pet', name: 'Dron Compañero', rarity: 'raro', price: 170, pk: 'dron' },
    { id: 'pet-dragon', cat: 'pet', name: 'Dragón Bebé', rarity: 'epico', price: 400, pk: 'dragon' },
    { id: 'pet-fenix', cat: 'pet', name: 'Polluelo de Fénix', rarity: 'legendario', price: 750, pk: 'fenix' },
    // ---- Armas (se ven en la mano y definen el estilo de disparo)
    { id: 'wp-rayo', cat: 'weapon', name: 'Varita Rayo', rarity: 'comun', price: 0, fx: 'bolt', held: 'wand', c1: '#ffe14a', c2: '#ff9f1c', desc: 'Dispara rayos amarillos.' },
    { id: 'wp-plasma', cat: 'weapon', name: 'Pistola de Plasma', rarity: 'raro', price: 90, fx: 'orb', held: 'blaster', c1: '#5ce1e6', c2: '#1b8fb3', desc: 'Dispara esferas de plasma cian.' },
    { id: 'wp-espada', cat: 'weapon', name: 'Espada de Caballero', rarity: 'raro', price: 130, fx: 'bolt', held: 'sword', c1: '#e8f1ff', c2: '#7d8aa3', desc: 'Lanza ondas de acero.' },
    { id: 'wp-mago', cat: 'weapon', name: 'Bastón de Mago', rarity: 'raro', price: 140, fx: 'orb', held: 'staff', c1: '#c77dff', c2: '#6d2bd1', desc: 'Dispara orbes arcanos.' },
    { id: 'wp-fuego', cat: 'weapon', name: 'Cetro de Fuego', rarity: 'raro', price: 150, fx: 'fire', held: 'staff', c1: '#ffb01f', c2: '#ff3b1f', desc: 'Lanza bolas de fuego.' },
    { id: 'wp-hielo', cat: 'weapon', name: 'Cetro de Hielo', rarity: 'raro', price: 150, fx: 'ice', held: 'staff', c1: '#d7f3ff', c2: '#66c8ff', desc: 'Dispara cristales de hielo.' },
    { id: 'wp-parabola', cat: 'weapon', name: 'Arco Parabólico', rarity: 'epico', price: 300, fx: 'wave', held: 'bow', c1: '#b980ff', c2: '#ff7ad9', desc: 'Disparo en onda, como una parábola.' },
    { id: 'wp-elfo', cat: 'weapon', name: 'Arco Élfico', rarity: 'epico', price: 320, fx: 'wave', held: 'bow', c1: '#7dff8a', c2: '#1fbf4a', desc: 'Flechas de luz verde.' },
    { id: 'wp-doble', cat: 'weapon', name: 'Láser Doble', rarity: 'epico', price: 350, fx: 'double', held: 'twin', c1: '#7dff8a', c2: '#1fbf4a', desc: 'Dos láseres a la vez.' },
    { id: 'wp-arcoiris', cat: 'weapon', name: 'Espada Arcoíris', rarity: 'legendario', price: 800, fx: 'rainbow', held: 'sword', c1: '#ff4d6d', c2: '#4da3ff', rainbow: true, desc: 'Un rayo de todos los colores.' },
    { id: 'wp-dragon', cat: 'weapon', name: 'Cetro Dracónico', rarity: 'legendario', price: 850, fx: 'fire', held: 'staff', c1: '#ff5a1f', c2: '#8c0f0f', dragon: true, desc: 'Aliento de dragón.' },
    { id: 'wp-duinity', cat: 'weapon', name: 'Espada Duinity', rarity: 'legendario', price: 0, fx: 'rainbow', held: 'sword', c1: '#ffd23f', c2: '#ff3b6b', gold: true, unlock: { ach: 'duinity' }, desc: 'Solo para quien vence a Duinity.' },
    // ---- Emblemas
    { id: 'emb-star', cat: 'emblem', name: 'Estrella', rarity: 'comun', price: 0, shape: 'star' },
    { id: 'emb-bolt', cat: 'emblem', name: 'Rayo', rarity: 'comun', price: 0, shape: 'bolt' },
    { id: 'emb-heart', cat: 'emblem', name: 'Corazón', rarity: 'comun', price: 40, shape: 'heart' },
    { id: 'emb-inf', cat: 'emblem', name: 'Infinito ∞', rarity: 'comun', price: 60, shape: 'inf' },
    { id: 'emb-pi', cat: 'emblem', name: 'Pi π', rarity: 'raro', price: 80, shape: 'pi' },
    { id: 'emb-sigma', cat: 'emblem', name: 'Sigma Σ', rarity: 'raro', price: 100, shape: 'sigma' },
    { id: 'emb-root', cat: 'emblem', name: 'Raíz √', rarity: 'raro', price: 100, shape: 'root' },
    { id: 'emb-flame', cat: 'emblem', name: 'Llama', rarity: 'epico', price: 160, shape: 'flame' },
    { id: 'emb-deriv', cat: 'emblem', name: 'Derivada f′', rarity: 'epico', price: 240, shape: 'deriv' },
    { id: 'emb-zero', cat: 'emblem', name: 'Indeterminado 0/0', rarity: 'legendario', price: 0, shape: 'zero', unlock: { ach: 'indeterminado' } },
    // ---- Amuletos (con ventaja)
    { id: 'am-none', cat: 'amulet', name: 'Sin amuleto', rarity: 'comun', price: 0, perk: 'Sin efecto.' },
    { id: 'am-escudo', cat: 'amulet', name: 'Escudo de Intervalos', rarity: 'raro', price: 200, perk: '+1 vida al empezar cada batalla.', hearts: 1 },
    { id: 'am-lupa', cat: 'amulet', name: 'Lupa Cartesiana', rarity: 'raro', price: 150, perk: 'Las pistas cuestan la mitad.', hintCost: 0.5 },
    { id: 'am-log', cat: 'amulet', name: 'Amuleto Logarítmico', rarity: 'epico', price: 300, perk: '+15% de monedas.', coins: 0.15 },
    { id: 'am-reloj', cat: 'amulet', name: 'Reloj de Arena', rarity: 'epico', price: 350, perk: 'Las respuestas caen 15% más lento.', slow: 0.15 },
    { id: 'am-titan', cat: 'amulet', name: 'Corazón de Titán', rarity: 'legendario', price: 700, perk: '+1 vida y ignora el primer golpe de cada batalla.', hearts: 1, shield: 1 },
    // ---- Emotes (bailes y gestos animados, como en Free Fire / Fortnite)
    { id: 'em-none', cat: 'emote', name: 'Sin emote', rarity: 'comun', price: 0, anim: 'none', fx: '' },
    { id: 'em-saludo', cat: 'emote', name: 'Saludo Héroe', rarity: 'comun', price: 0, anim: 'wave', fx: '👋', desc: 'El saludo clásico de todo superhéroe.' },
    { id: 'em-baile', cat: 'emote', name: 'Baile Arcade', rarity: 'comun', price: 0, anim: 'sway', fx: '🎵', desc: 'Mueve el esqueleto al ritmo del chiptune.' },
    { id: 'em-salto', cat: 'emote', name: 'Salto Victoria', rarity: 'comun', price: 0, anim: 'hop', fx: '⭐', desc: '¡Saltos de campeón!' },
    { id: 'em-giro', cat: 'emote', name: 'Giro Ninja', rarity: 'raro', price: 150, anim: 'spin', fx: '💨', desc: 'Giras como un trompo ninja.' },
    { id: 'em-robot', cat: 'emote', name: 'Robot Retro', rarity: 'raro', price: 180, anim: 'robot', fx: '⚙️', desc: 'Bip bop: movimientos de robot.' },
    { id: 'em-floss', cat: 'emote', name: 'Floss Fantasma', rarity: 'raro', price: 220, anim: 'floss', fx: '✨', desc: 'El baile más viral de la galaxia.' },
    { id: 'em-latido', cat: 'emote', name: 'Corazón Loco', rarity: 'raro', price: 200, anim: 'pulse', fx: '❤️', desc: 'Tu corazón late por el cálculo.' },
    { id: 'em-mortal', cat: 'emote', name: 'Mortal Atrás', rarity: 'epico', price: 320, anim: 'flip', fx: '💥', desc: 'Voltereta hacia atrás con explosión.' },
    { id: 'em-moon', cat: 'emote', name: 'Moonwalk Neón', rarity: 'epico', price: 350, anim: 'moon', fx: '🌙', desc: 'Deslízate hacia atrás como una estrella.' },
    { id: 'em-tornado', cat: 'emote', name: 'Tornado', rarity: 'epico', price: 380, anim: 'tornado', fx: '🌀', desc: 'Un remolino de pura energía.' },
    { id: 'em-temblor', cat: 'emote', name: 'Terremoto', rarity: 'epico', price: 300, anim: 'shake', fx: '💢', desc: 'Sacude toda la pista.' },
    { id: 'em-rey', cat: 'emote', name: 'Rey del Baile', rarity: 'legendario', price: 600, anim: 'king', fx: '👑', desc: 'Combo de giros, saltos y poses reales.' },
    { id: 'em-sigma', cat: 'emote', name: 'Danza Sigma', rarity: 'legendario', price: 700, anim: 'sigma', fx: 'Σ', desc: 'La danza secreta de los matemáticos.' },
  ];
  const ITEM_BY_ID = Object.fromEntries(ITEMS.map((i) => [i.id, i]));

  const SKINS = ['#ffdcb8', '#f5c193', '#d9a066', '#b97a4a', '#8a5533', '#5c3720'];
  const HAIR_COLORS = ['#1a1033', '#4a2c17', '#a0522d', '#e8c15a', '#d64545', '#3aa0ff', '#9b5de5', '#f2f2f2'];
  const BASE_SUITS = { m: ['suit-rojo', 'suit-azul', 'suit-verde', 'suit-amarillo'], f: ['suit-rosa', 'suit-morado', 'suit-cian', 'suit-naranja'] };
  const FREE_HAIR = ['hair-corto', 'hair-pinchos', 'hair-calvo', 'hair-largo', 'hair-coleta'];

  /* ---------- Logros ---------- */
  // check(stats, save) => progreso actual (número); goal = meta
  const ACH = [
    { id: 'primera', name: 'Primera victoria', desc: 'Derrota a tu primer villano.', goal: 1, prog: (s) => s.wins, coins: 30 },
    { id: 'diez', name: 'Calentando motores', desc: 'Responde 50 preguntas bien.', goal: 50, prog: (s) => s.correct, coins: 40 },
    { id: 'cien', name: 'Cerebro en llamas', desc: 'Responde 250 preguntas bien.', goal: 250, prog: (s) => s.correct, coins: 100, item: 'emb-heart' },
    { id: 'mil', name: 'Enciclopedia andante', desc: 'Responde 1000 preguntas bien.', goal: 1000, prog: (s) => s.correct, coins: 400, item: 'suit-plata' },
    { id: 'racha5', name: 'En racha', desc: 'Logra una racha de 5 aciertos.', goal: 5, prog: (s) => s.bestStreak, coins: 25 },
    { id: 'racha12', name: 'Imparable', desc: 'Logra una racha de 12 aciertos.', goal: 12, prog: (s) => s.bestStreak, coins: 80, item: 'wp-plasma' },
    { id: 'racha25', name: 'Máquina de límites', desc: 'Logra una racha de 25 aciertos.', goal: 25, prog: (s) => s.bestStreak, coins: 200 },
    { id: 'villanos5', name: 'Cazador de villanos', desc: 'Derrota a 5 villanos distintos.', goal: 5, prog: (s) => s.districts, coins: 60 },
    { id: 'villanos14', name: 'Guardián de la Ciudad', desc: 'Derrota a los 15 villanos.', goal: 15, prog: (s) => s.districts, coins: 250, item: 'mask-visor' },
    { id: 'perfecto', name: 'Sin rasguños', desc: 'Gana una batalla sin perder ninguna vida.', goal: 1, prog: (s) => s.perfect, coins: 40 },
    { id: 'perfecto5', name: 'Intocable', desc: 'Gana 5 batallas sin perder ninguna vida.', goal: 5, prog: (s) => s.perfect, coins: 150, item: 'cape-larga-negra' },
    { id: 'estrellas', name: 'Coleccionista de estrellas', desc: 'Consigue 25 estrellas en total.', goal: 25, prog: (s) => s.stars, coins: 100 },
    { id: 'estrellas42', name: 'Cielo despejado', desc: 'Consigue las 45 estrellas del mapa.', goal: 45, prog: (s) => s.stars, coins: 400, item: 'suit-dorado' },
    { id: 'heroico', name: 'Modo heroico', desc: 'Gana en dificultad Difícil.', goal: 1, prog: (s) => s.hardWins, coins: 80 },
    { id: 'nivel5', name: 'Héroe en ascenso', desc: 'Llega al nivel 5.', goal: 5, prog: (s) => s.level, coins: 60 },
    { id: 'nivel10', name: 'Leyenda de Ciudad Límite', desc: 'Llega al nivel 10.', goal: 10, prog: (s) => s.level, coins: 200 },
    { id: 'tienda', name: 'De compras', desc: 'Compra tu primer objeto.', goal: 1, prog: (s) => s.purchases, coins: 20 },
    { id: 'coleccion', name: 'Guardarropa heroico', desc: 'Ten 15 objetos en tu colección.', goal: 15, prog: (s) => s.owned, coins: 120 },
    { id: 'indeterminado', name: 'Dividido por cero', desc: 'Derrota a El Indeterminado.', goal: 1, prog: (s) => s.boss, coins: 300 },
    { id: 'duinity', name: 'Más allá del infinito', desc: 'Llega a 25 respuestas correctas en el modo Duinity.', goal: 25, prog: (s) => s.duinityBest, coins: 500 },
  ];

  /* ---------- Misiones diarias ---------- */
  const MISSIONS = [
    { id: 'm-correct15', name: 'Responde 15 preguntas bien', goal: 15, stat: 'correct', reward: 30 },
    { id: 'm-correct30', name: 'Responde 30 preguntas bien', goal: 30, stat: 'correct', reward: 55 },
    { id: 'm-streak5', name: 'Logra una racha de 5', goal: 5, stat: 'streak', reward: 30 },
    { id: 'm-win2', name: 'Gana 2 batallas', goal: 2, stat: 'wins', reward: 45 },
    { id: 'm-win1', name: 'Gana 1 batalla', goal: 1, stat: 'wins', reward: 25 },
    { id: 'm-perfect', name: 'Gana una batalla sin perder vidas', goal: 1, stat: 'perfect', reward: 50 },
    { id: 'm-districts2', name: 'Juega 2 distritos distintos', goal: 2, stat: 'districts', reward: 35 },
  ];

  const AUTHOR = { name: 'Deiwy', full: 'Deiwy', career: 'Estadística', course: 'Cálculo Diferencial', book: 'Stewart, Precálculo', year: 2026 }; // ← pon aquí tu nombre completo
  const DATA = { AUTHOR, VILLAINS, REPASO, RARITY, CATS, ITEMS, ITEM_BY_ID, SKINS, HAIR_COLORS, BASE_SUITS, FREE_HAIR, ACH, MISSIONS };
  if (typeof module !== 'undefined' && module.exports) module.exports = DATA; else root.DuiXData = DATA;
})(typeof window !== 'undefined' ? window : globalThis);
